/*OPERADORES
    OPERADOR DE ASIGNACION.
        =  SE USA PARA ASIGNAR VALORES A UNA VARIABLE
        += SUMA UN NUMERO AL VALOR DE UNA VARIABLE
        -= RESTA UN NUMERO AL VALOR DE UNA VARIABLE
        *= MULTIPLICA UN NUMERO AL VALOR DE UNA VARIABLE
        /= DIVIDE UN NUMERO AL VALOR DE UNA VARIABLE
        %= OBTIENE EL SOBRANTE DE UNA DIVISION Y LO ASIGNA A LA VARIABLE
    OPERADORES ARITMETICOS:
        + SUMA
        - RESTA
        * MULTIPLICACION
        / DIVISION
        % MODULO
        ++ AUMENTO
        -- DISMINUCION
    OPERADORES DE COMPARACION:
        ==IGUAL QUE
        === IGUAL EN VALOR Y TIPO DE DATO
        != DIFERENTE
        !== DIFERENTE EN VALOR Y TIPO DE DATO
        < MENOR QUE
        > MAYOR QUE
        <= MENOR O IGUAL QUE
        >= MAYOR O IGUAL QUE
        ? OPERADOR TERNIARIO
*/
//SUMA
let resultado = 5 + 5;
let suma=4;

//RESTA
resultado = 80 - 20;
let resta=10;

//MULTIPLICACION
resultado = 3 * 9;

//DIVISION
resultado = 10 / 2;

//MODULO--- PERMITE OBTENER EL SOBRANTE DE UNA DIVISION Y LO ASIGNA A LA VARIABLE
resultado = 10 % 3;
console.log(resultado)

//AUMENTO Y DISMINUCION
let numero = 10;
//numero= numero +1-------FORMA BASICA DE AUMENTAR UN VALOR
numero++
numero--
console.log(numero);

/*OPERADORES DE ASIGNACION
    += SUMA UN NUMERO AL VALOR DE UNA VARIABLE
    -= RESTA UN NUMERO AL VALOR DE UNA VARIABLE
    *= MULTIPLICA UN NUMERO AL VALOR DE UNA VARIABLE
    /= DIVIDE UN NUMERO AL VALOR DE UNA VARIABLE
    %= OBTIENE EL SOBRANTE DE UNA DIVISION Y LO ASIGNA A LA VARIABLE
*/
//SUMA
let valor = 10;
//valor = valor + 6
valor +=6;                    
//RESTA
valor -=2;
//MULTIPLICACION
valor *=10               //DE ESTA MANERA LAS OPERACIONES SERAN CONTINUAS Y EL RESULTADO SERA ASIGNADO A LA VARIABLE
//DIVISION
valor /=2
console.log(valor)

//OPERADORES DE COMPARACION
let num = 3 > 1;
num = 8<10;
num = 10 === '10';  
console.log(num);

//OPERADOR TERNIARIO
let number = 3>10 ? 'EL 3 ES MAYOR' : 'EL 3 NO ES MAYOR'     //ESTE OPERADOR REALIZA UNA PEQUEÑA CONDICION DE ACUERDO A UNA COMPARACION DE VALORES
console.log(number);

/*
EJERCICIO 1
REALIZAR LA SUMA, RESTA, MULTIPLICACION Y DIVISION DE 20 Y 40, LA OPERACION DEBE SER CONTINUA

EJERCICIO 2
MOSTRARME POR CONSOLA SI EL PRIMER VALOR ES MAYOR QUE EL SEGUNDO, SI NO LO ES, MOSTRAR QUE EL PRIMER VALOR ES MENOR QUE EL SEGUNDO
*/